# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cyber/proto/simple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.common_msgs.basic_msgs import header_pb2 as modules_dot_common__msgs_dot_basic__msgs_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cyber/proto/simple.proto',
  package='apollo.cyber.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x18\x63yber/proto/simple.proto\x12\x12\x61pollo.cyber.proto\x1a+modules/common_msgs/basic_msgs/header.proto\"U\n\rSimpleMessage\x12\x0f\n\x07integer\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12%\n\x06header\x18\x03 \x01(\x0b\x32\x15.apollo.common.Header\"K\n\x15SimpleRepeatedMessage\x12\x32\n\x07message\x18\x01 \x03(\x0b\x32!.apollo.cyber.proto.SimpleMessage')
  ,
  dependencies=[modules_dot_common__msgs_dot_basic__msgs_dot_header__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SIMPLEMESSAGE = _descriptor.Descriptor(
  name='SimpleMessage',
  full_name='apollo.cyber.proto.SimpleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='integer', full_name='apollo.cyber.proto.SimpleMessage.integer', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='apollo.cyber.proto.SimpleMessage.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='header', full_name='apollo.cyber.proto.SimpleMessage.header', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=178,
)


_SIMPLEREPEATEDMESSAGE = _descriptor.Descriptor(
  name='SimpleRepeatedMessage',
  full_name='apollo.cyber.proto.SimpleRepeatedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='apollo.cyber.proto.SimpleRepeatedMessage.message', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=255,
)

_SIMPLEMESSAGE.fields_by_name['header'].message_type = modules_dot_common__msgs_dot_basic__msgs_dot_header__pb2._HEADER
_SIMPLEREPEATEDMESSAGE.fields_by_name['message'].message_type = _SIMPLEMESSAGE
DESCRIPTOR.message_types_by_name['SimpleMessage'] = _SIMPLEMESSAGE
DESCRIPTOR.message_types_by_name['SimpleRepeatedMessage'] = _SIMPLEREPEATEDMESSAGE

SimpleMessage = _reflection.GeneratedProtocolMessageType('SimpleMessage', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEMESSAGE,
  __module__ = 'cyber.proto.simple_pb2'
  # @@protoc_insertion_point(class_scope:apollo.cyber.proto.SimpleMessage)
  ))
_sym_db.RegisterMessage(SimpleMessage)

SimpleRepeatedMessage = _reflection.GeneratedProtocolMessageType('SimpleRepeatedMessage', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEREPEATEDMESSAGE,
  __module__ = 'cyber.proto.simple_pb2'
  # @@protoc_insertion_point(class_scope:apollo.cyber.proto.SimpleRepeatedMessage)
  ))
_sym_db.RegisterMessage(SimpleRepeatedMessage)


# @@protoc_insertion_point(module_scope)
