# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/lidar_detection_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/lidar_detection_config.proto',
  package='apollo.perception.pipeline',
  syntax='proto2',
  serialized_pb=_b('\n>modules/perception/pipeline/proto/lidar_detection_config.proto\x12\x1a\x61pollo.perception.pipeline\"+\n\x14LidarDetectionConfig\x12\x13\n\x0bsensor_name\x18\x01 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LIDARDETECTIONCONFIG = _descriptor.Descriptor(
  name='LidarDetectionConfig',
  full_name='apollo.perception.pipeline.LidarDetectionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_name', full_name='apollo.perception.pipeline.LidarDetectionConfig.sensor_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['LidarDetectionConfig'] = _LIDARDETECTIONCONFIG

LidarDetectionConfig = _reflection.GeneratedProtocolMessageType('LidarDetectionConfig', (_message.Message,), dict(
  DESCRIPTOR = _LIDARDETECTIONCONFIG,
  __module__ = 'modules.perception.pipeline.proto.lidar_detection_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.pipeline.LidarDetectionConfig)
  ))
_sym_db.RegisterMessage(LidarDetectionConfig)


# @@protoc_insertion_point(module_scope)
