# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/traffic_light_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/traffic_light_config.proto',
  package='apollo.perception.pipeline',
  syntax='proto2',
  serialized_pb=_b('\n<modules/perception/pipeline/proto/traffic_light_config.proto\x12\x1a\x61pollo.perception.pipeline\"%\n\x10PerceptionConfig\x12\x11\n\x06gpu_id\x18\x01 \x01(\x05:\x01\x30\"k\n\x12TrafficLightConfig\x12U\n\x1ftrafficlights_perception_config\x18\x01 \x01(\x0b\x32,.apollo.perception.pipeline.PerceptionConfig')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PERCEPTIONCONFIG = _descriptor.Descriptor(
  name='PerceptionConfig',
  full_name='apollo.perception.pipeline.PerceptionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gpu_id', full_name='apollo.perception.pipeline.PerceptionConfig.gpu_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=129,
)


_TRAFFICLIGHTCONFIG = _descriptor.Descriptor(
  name='TrafficLightConfig',
  full_name='apollo.perception.pipeline.TrafficLightConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trafficlights_perception_config', full_name='apollo.perception.pipeline.TrafficLightConfig.trafficlights_perception_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=238,
)

_TRAFFICLIGHTCONFIG.fields_by_name['trafficlights_perception_config'].message_type = _PERCEPTIONCONFIG
DESCRIPTOR.message_types_by_name['PerceptionConfig'] = _PERCEPTIONCONFIG
DESCRIPTOR.message_types_by_name['TrafficLightConfig'] = _TRAFFICLIGHTCONFIG

PerceptionConfig = _reflection.GeneratedProtocolMessageType('PerceptionConfig', (_message.Message,), dict(
  DESCRIPTOR = _PERCEPTIONCONFIG,
  __module__ = 'modules.perception.pipeline.proto.traffic_light_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.pipeline.PerceptionConfig)
  ))
_sym_db.RegisterMessage(PerceptionConfig)

TrafficLightConfig = _reflection.GeneratedProtocolMessageType('TrafficLightConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICLIGHTCONFIG,
  __module__ = 'modules.perception.pipeline.proto.traffic_light_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.pipeline.TrafficLightConfig)
  ))
_sym_db.RegisterMessage(TrafficLightConfig)


# @@protoc_insertion_point(module_scope)
