# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/dreamview/backend/sim_control_manager/proto/dynamic_model_conf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/dreamview/backend/sim_control_manager/proto/dynamic_model_conf.proto',
  package='apollo.dreamview',
  syntax='proto2',
  serialized_pb=_b('\nLmodules/dreamview/backend/sim_control_manager/proto/dynamic_model_conf.proto\x12\x10\x61pollo.dreamview\"a\n\x10\x44ynamicModelConf\x12\x1a\n\x12\x64ynamic_model_name\x18\x01 \x01(\t\x12\x14\n\x0clibrary_name\x18\x02 \x01(\t\x12\x1b\n\x13\x64ynamic_model_files\x18\x03 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DYNAMICMODELCONF = _descriptor.Descriptor(
  name='DynamicModelConf',
  full_name='apollo.dreamview.DynamicModelConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dynamic_model_name', full_name='apollo.dreamview.DynamicModelConf.dynamic_model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='library_name', full_name='apollo.dreamview.DynamicModelConf.library_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dynamic_model_files', full_name='apollo.dreamview.DynamicModelConf.dynamic_model_files', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=195,
)

DESCRIPTOR.message_types_by_name['DynamicModelConf'] = _DYNAMICMODELCONF

DynamicModelConf = _reflection.GeneratedProtocolMessageType('DynamicModelConf', (_message.Message,), dict(
  DESCRIPTOR = _DYNAMICMODELCONF,
  __module__ = 'modules.dreamview.backend.sim_control_manager.proto.dynamic_model_conf_pb2'
  # @@protoc_insertion_point(class_scope:apollo.dreamview.DynamicModelConf)
  ))
_sym_db.RegisterMessage(DynamicModelConf)


# @@protoc_insertion_point(module_scope)
