# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/bev_detection_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/bev_detection_config.proto',
  package='apollo.perception.camera.bev',
  syntax='proto2',
  serialized_pb=_b('\nBmodules/perception/pipeline/proto/stage/bev_detection_config.proto\x12\x1c\x61pollo.perception.camera.bev\"\x14\n\x12\x42\x45VDetectionConfig')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BEVDETECTIONCONFIG = _descriptor.Descriptor(
  name='BEVDetectionConfig',
  full_name='apollo.perception.camera.bev.BEVDetectionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['BEVDetectionConfig'] = _BEVDETECTIONCONFIG

BEVDetectionConfig = _reflection.GeneratedProtocolMessageType('BEVDetectionConfig', (_message.Message,), dict(
  DESCRIPTOR = _BEVDETECTIONCONFIG,
  __module__ = 'modules.perception.pipeline.proto.stage.bev_detection_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.bev.BEVDetectionConfig)
  ))
_sym_db.RegisterMessage(BEVDetectionConfig)


# @@protoc_insertion_point(module_scope)
