# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/object_builder_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/stage/object_builder_config.proto',
  package='apollo.perception.lidar',
  syntax='proto2',
  serialized_pb=_b('\nCmodules/perception/pipeline/proto/stage/object_builder_config.proto\x12\x17\x61pollo.perception.lidar\"\x15\n\x13ObjectBuilderConfig')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OBJECTBUILDERCONFIG = _descriptor.Descriptor(
  name='ObjectBuilderConfig',
  full_name='apollo.perception.lidar.ObjectBuilderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['ObjectBuilderConfig'] = _OBJECTBUILDERCONFIG

ObjectBuilderConfig = _reflection.GeneratedProtocolMessageType('ObjectBuilderConfig', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTBUILDERCONFIG,
  __module__ = 'modules.perception.pipeline.proto.stage.object_builder_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.ObjectBuilderConfig)
  ))
_sym_db.RegisterMessage(ObjectBuilderConfig)


# @@protoc_insertion_point(module_scope)
