# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/plugin/get_image_data_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/pipeline/proto/plugin/get_image_data_config.proto',
  package='apollo.perception.camera',
  syntax='proto2',
  serialized_pb=_b('\nDmodules/perception/pipeline/proto/plugin/get_image_data_config.proto\x12\x18\x61pollo.perception.camera\"k\n\x12GetImageDataConfig\x12\x1a\n\x12image_origin_width\x18\x01 \x01(\x05\x12\x1b\n\x13image_origin_height\x18\x02 \x01(\x05\x12\x1c\n\x14image_origin_channel\x18\x03 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETIMAGEDATACONFIG = _descriptor.Descriptor(
  name='GetImageDataConfig',
  full_name='apollo.perception.camera.GetImageDataConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_origin_width', full_name='apollo.perception.camera.GetImageDataConfig.image_origin_width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_origin_height', full_name='apollo.perception.camera.GetImageDataConfig.image_origin_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_origin_channel', full_name='apollo.perception.camera.GetImageDataConfig.image_origin_channel', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=205,
)

DESCRIPTOR.message_types_by_name['GetImageDataConfig'] = _GETIMAGEDATACONFIG

GetImageDataConfig = _reflection.GeneratedProtocolMessageType('GetImageDataConfig', (_message.Message,), dict(
  DESCRIPTOR = _GETIMAGEDATACONFIG,
  __module__ = 'modules.perception.pipeline.proto.plugin.get_image_data_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.GetImageDataConfig)
  ))
_sym_db.RegisterMessage(GetImageDataConfig)


# @@protoc_insertion_point(module_scope)
